### ISSUE TITLE
Create favorites for MicroBlogPost

### ISSUE THREAD

**Issue by vnu** [vimalathithanr/MicroBlogPost#3]
- [x] On my timeline, against each Micropost, show favorite link with count 
- [x] If I have already favorited, show unfavorite with count
- [x] Your favorite url endpoint /microposts/:id/favorite (Refer adding routes on: :member)
- [x] Unfavorite url endpoint /microposts/:id/unfavorite

**Comment by vimalathithanr** [comment]
I have added favorites controller. But I am not sure whether I really want a controller for favorites. I can actually implement the method in model/micropost.rb (as I can access both the user_id and micropost_id here)

**Comment by vnu** [comment]
@vimalathithanr I have explicit favorite endpoint requirement above. Please check.

**Comment by vimalathithanr** [comment]
@vnu  Check and please let me know how I am doing.

**Comment by vimalathithanr** [comment]
<% if current_micrpost_favorite?(micropost) %>
       <%= link_to "unfavorite", micropost, :remote => true, method: :post, :id => "unfavorite_link" %>
    <% else %>
        <%= link_to "favorite", :controller => "microposts", :action => "favorite", :id => micropost.id %>
    <%end%>

**Comment by vnu** [comment]
```ruby 
<%= link_to "favorite",  favorite_micropost_url(micropost) %>
```

**Comment by vimalathithanr** [comment]
def favorite
    favorite = Favorite.new
    favorite.micropost_id = :id
    favorite.user_id = :user_id
    favorite.save
  end

**Comment by vimalathithanr** [comment]
def favorite
favorite = Favorite.new
favorite.micropost_id = "3"
favorite.user_id = "1"
favorite.save
end

**Comment by vnu** [comment]
```ruby
1.9.3-p551 :004 > hash1 = {"a" => 'vc', "b" => 'vmal'}
 => {"a"=>"vc", "b"=>"vmal"}
1.9.3-p551 :005 > hash1['a']
 => "vc"
1.9.3-p551 :006 > hash1[:a]
 => nil
1.9.3-p551 :007 > hash1 = {:a => 'vc', :b => 'vmal'}
 => {:a=>"vc", :b=>"vmal"}
1.9.3-p551 :008 > hash1['a']
 => nil
1.9.3-p551 :009 > hash1[:a]
 => "vc"
```

**Comment by vnu** [comment]
```ruby
:a
//You are expecting 'vc'
```

**Comment by vimalathithanr** [comment]
@vnu Shall I go ahead and merge with master branch?

**Comment by vimalathithanr** [comment]
Closing this issue.
