### ISSUE TITLE
current_user not found error

### ISSUE THREAD

**Issue by vnu** [vimalathithanr/MicroBlogPost#4]

**Comment by vimalathithanr** [comment]
Showing C:/Sites/sample_app/app/views/users/_follow_form.html.erb where line #1 raised:

undefined method `current_user?' for #<#<Class:0xa175c28>:0x9bb7670>
Trace of template inclusion: app/views/users/show.html.erb

Rails.root: C:/Sites/sample_app

Application Trace | Framework Trace | Full Trace
app/views/users/_follow_form.html.erb:1:in `_app_views_users__follow_form_html_erb__963594488_81831192'
app/views/users/show.html.erb:15:in `_app_views_users_show_html_erb__852972838_81638592'

**Comment by vimalathithanr** [comment]
Started GET "/users/1" for ::1 at 2015-08-17 20:13:10 -0700
Processing by UsersController#show as HTML
  Parameters: {"id"=>"1"}
  [1m[36mUser Load (0.0ms)[0m  [1mSELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1[0m  [["id", 1]]
  [1m[35m (0.0ms)[0m  SELECT COUNT(*) FROM "users" INNER JOIN "relationships" ON "users"."id" = "relationships"."followed_id" WHERE "relationships"."follower_id" = ?  [["follower_id", 1]]
  [1m[36m (0.0ms)[0m  [1mSELECT COUNT(*) FROM "users" INNER JOIN "relationships" ON "users"."id" = "relationships"."follower_id" WHERE "relationships"."followed_id" = ?[0m  [["followed_id", 1]]
  Rendered shared/_stats.html.erb (18.0ms)
  [1m[35mUser Load (0.0ms)[0m  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 9]]
  [1m[36mMicropost Load (1.0ms)[0m  [1mSELECT  "microposts".* FROM "microposts" WHERE "microposts"."user_id" = ?  ORDER BY "microposts"."created_at" DESC LIMIT 30 OFFSET 0[0m  [["user_id", 1]]
  Rendered users/_follow_form.html.erb (29.2ms)
  Rendered users/show.html.erb within layouts/application (51.3ms)
Completed 500 Internal Server Error in 65ms (ActiveRecord: 1.0ms)

ActionView::Template::Error (undefined method `current_user?' for #<#<Class:0xa175c28>:0x3a1cb80>):
    1: <% unless current_user?(@user) %>
    2:   <div id="follow_form">
    3:   <% if current_user.following?(@user) %>
    4:     <%= render 'unfollow' %>
  app/views/users/_follow_form.html.erb:1:in `_app_views_users__follow_form_html_erb__963594488_81831192'
  app/views/users/show.html.erb:15:in `_app_views_users_show_html_erb__852972838_81638592'


  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (10.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (80.4ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (1.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (1.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (71.1ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (1.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (1.0ms)
  Rendered C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (156.6ms)

**Comment by vimalathithanr** [comment]
Completed 500 Internal Server Error in 65ms (ActiveRecord: 2.0ms)

ActionView::Template::Error (undefined method `current_user?' for #<#<Class:0x9ef8dd0>:0x9ef86e0>):
    1: <% unless current_user?(@user) %>
    2:   <div id="follow_form">
    3:   <% if current_user.following?(@user) %>
    4:     <%= render 'unfollow' %>
  app/views/users/_follow_form.html.erb:1:in `_app_views_users__follow_form_html_erb__666986837_83708808'
  app/views/users/show.html.erb:15:in `_app_views_users_show_html_erb___1030529060_83524908'

**Comment by vimalathithanr** [comment]
Fixed this issue with a code change. Hence closing.
