### ISSUE TITLE
Research on Counter Caching

### ISSUE THREAD

**Issue by vimalathithanr** [vimalathithanr/MicroBlogPost#7]

**Comment by vimalathithanr** [comment]
Found this tutorial to start with:
https://www.youtube.com/watch?v=0VJ5lvswXSY

**Comment by vnu** [comment]
Check out http://railscasts.com/ This has many such videos

**Comment by vimalathithanr** [comment]
I have subscribed to Rails cast.

**Comment by vimalathithanr** [comment]
Note: I can implement counter caching here for each microblog post. Since favorites table is getting called for each record. Again counter caching can be implemented by eager loading but the performance is going to be the same. 

Adding column count to the micropost table will drastically reduce the performance issue.
