### ISSUE TITLE
Create Micropost details

### ISSUE THREAD

**Issue by vimalathithanr** [vimalathithanr/MicroBlogPost#8]
Show micropost details in a separate window with the following details:
1. Number of favorites
2. List of users for favorited the post

**Comment by vnu** [comment]
```ruby
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost

scope :with_user, lambda { includes(:user)}

  validates :user_id, presence: true
  validates :micropost_id, presence: true

end

### In Controller
def show
  if micropost
   @favorites = micropost.favorites.with_user
  end
end


#### In view
@favorites.each do |favorite|
   favorite.user.name
end

```

**Comment by vimalathithanr** [comment]
@vnu  I have started reading API rails documentation:
Scope: Adds a class method for retrieving and querying objects. A scope represents a narrowing of a database query, such as where(color: :red).select('shirts.*').includes(:washing_instructions). 
Thanks!
